# Generated by Django 2.0 on 2018-08-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanist_app', '0002_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='pw_reset_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='pw_reset_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
