# Generated by Django 2.0 on 2018-08-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanist_app', '0003_auto_20180807_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingemail',
            name='log',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
