# Generated by Django 2.0 on 2018-08-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanist_app', '0004_incomingemail_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingemail',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
