# Generated by Django 2.0 on 2018-09-11 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humanist_app', '0005_auto_20180817_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=128)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humanist_app.IncomingEmail')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
