# Generated by Django 2.0 on 2018-09-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanist_app', '0006_email_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='issue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
