# Generated by Django 2.0 on 2018-10-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanist_app', '0007_volume_and_issues'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
    ]
