# Generated by Django 2.0 on 2018-11-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanist_app', '0008_subscriber-ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='digest',
            field=models.BooleanField(default=False, verbose_name='Receive Digest?'),
        ),
    ]
