# Generated by Django 2.0 on 2018-11-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanist_app', '0012_auto_20181101_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='bounce_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='bounce_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
