# Generated by Django 2.2 on 2020-05-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanist_app', '0014_manual-editing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('filename', models.CharField(max_length=2048)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='editedemail',
            options={'ordering': ['order_no', 'subject']},
        ),
    ]
